# numpy is the core library for the multidimensional array

# it is a table of elements (usually numbers), all of the same type, indexes by a typle of positive integers

# in numpy, dimensions are called axes

# numpy array vs python list
    
    why should we use numpy array when we have python list
    
    ~Fast        ~convenient         ~less memory

In [3]:
import numpy as np            # import the module and called numpy as np

a=np.array([1,8,5])
print(a)

[1 8 5]


In [4]:
import numpy as np         

a=np.array([1,8,5])              # same as the above code
a

array([1, 8, 5])

In [9]:
import numpy as np

a=np.array([1,8,5])
print(a[1])

8


In [5]:
import time 
import sys

In [68]:
b=range(100)
print(sys.getsizeof(5)*len(b))

2800


In [54]:
c=np.arange(10000)
print(c.size*c.itemsize)

40000


In [7]:
size=100
L1=range(size)
L2=range(size)
A1=np.arange(size)
A2=np.arange(size)
start=time.time()
result = [(x+y) for x,y in zip(L1, L2)]
print(result)
print("python list took:", (time.time()-start)*100)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198]
python list took: 0.0


In [100]:
start=time.time()
result=A1+A2
print("python array took:", (time.time()-start)*100000)

python array took: 1013.6127471923828


# Basic operations

In [132]:
b=np.array([[1,2],[4,6],[7,8]])
b

array([[1, 2],
       [4, 6],
       [7, 8]])

In [133]:
b.ndim

2

In [134]:
b.itemsize

4

In [135]:
b.shape    # rows and column

(3, 2)

In [136]:
b=np.array([[1,2],[4,6],[7,8]], dtype=np.float64)
b

array([[1., 2.],
       [4., 6.],
       [7., 8.]])

In [138]:
b.itemsize

8

In [139]:
b.shape

(3, 2)

In [140]:
np.zeros((3,4))             # Three rows and four columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [141]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [151]:
l=range(6)       # The range is 0 to 6
l

range(0, 6)

In [152]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [157]:
print(np.char.add(["Hi","Hello"],["Welcome", "Again"]))       # Concatenation strings

['HiWelcome' 'HelloAgain']


In [158]:
np.char.add(["Hi","Hello"],["Welcome", "Again"])       # same as the above code

array(['HiWelcome', 'HelloAgain'], dtype='<U12')

In [165]:
print(np.char.multiply("Hi", 3))                     # multiply the given value three times

HiHiHi


In [176]:
print(np.char.center("Hi", 20,fillchar="-"))         # Align the string to center

---------Hi---------


In [180]:
print(np.char.capitalize("hi hello"))               # The first letter will be capitalized

Hi hello


In [183]:
print(np.char.title("Where are you from?"))        # Each word first letter will be capital using title

Where Are You From?


In [184]:
print(np.char.lower("HI HELLO GUYS"))             # print the string in lower case

hi hello guys


In [185]:
print(np.char.upper("welocme you all"))             # print the string in upper case

WELOCME YOU ALL


In [186]:
print(np.char.split("where are you from?"))             # split the string

['where', 'are', 'you', 'from?']


In [189]:
print(np.char.splitlines("where\n are you from?"))  # split two lines because we using the \n 

['where', ' are you from?']


In [197]:
print(np.char.strip(["apple","admin","anual"],"a"))   # Remove _a_ in each word only the first letter

['pple' 'dmin' 'nual']


In [203]:
print(np.char.join([":","/"],["dmy","ymd"]))           # join the word and symbols

['d:m:y' 'y/m/d']


In [208]:
print(np.char.replace("he is a good dancer","is","was"))    # replace the word _is_

he was a good dancer
